GET http://localhost:4000/

####

POST http://localhost:4000/
Content-Type: application/json

{
    "bien": "gia tri"
}

####

GET http://localhost:4000/users
Content-Type: application/json

####

POST http://localhost:4000/users

####

PUT http://localhost:4000/users

####

DELETE http://localhost:4000/users

####

GET http://localhost:4000/User/20
GET http://localhost:4000/User/

####

GET http://localhost:4000/User/muayarmy123@gmail.com

####

POST http://localhost:4000/User
Content-Type: application/json
Authorization: Basic eHVhbm5ndXllbjowNDA5MDA= 

{
    "name": "Xuan Nguyen",
    "account": "xuannguyen",
    "password": "040900",
    "email": "muayarmy123@gmail.com"
}

####

POST http://localhost:4000/User/sign-up
Content-Type: application/json

{
    "name": "Xuan Nguyen",
    "account": "xuannguyen",
    "password": "040900",
    "email": "muayarmy123@gmail.com"
}

####

POST http://localhost:4000/users
Content-Type: application/json
Authorization: Basic eHVhbm5ndXllbjowNDA5MDA=

[
    {
        "name": "Xuan Nguyen",
        "account": "xuannguyen",
        "password": "040900",
        "email": "muayarmy123@gmail.com"
    },
    {
        "name": "Nguyen Xuan",
        "account": "nkoxngo",
        "password": "123456",
        "email": "nkoxkiu2k@gmail.com"
    },
    {
        "name": "Ami Nguyen",
        "account": "xuannguyen",
        "password": "xuan2000",
        "email": "nguyenthihaxuan040900hiie@gmail.com"
    },
    {
        "name": "Emi Nguyen",
        "account": "nguyenxuan",
        "password": "01665017740",
        "email": "ahihidocho@gmail.com"
    }
]

####

PUT http://localhost:4000/User/nguyenthihaxuan040900hiie@gmail.com
Content-Type: application/json

{
    "name": "Xuan Nguyen",
    "account": "xuannguyen",
    "password": "040900",
    "email": "muayarmy321@gmail.com"
}

####

DELETE http://localhost:4000/User/nguyenthihaxuan040900hiie@gmail.com
Content-Type: application/json
Authorization: Basic eHVhbm5ndXllbjowNDA5MDA=
